# Basic oh-my-zsh config
export ZSH="/Users/frank/.config/oh-my-zsh"
ZSH_AUTOSUGGEST_STRATEGY=(history completion)
ZSH_THEME="powerlevel10k/powerlevel10k"
POWERLEVEL9K_LEFT=(user dir vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status vi-mode public_ip)
POWERLEVEL9K_CONTEXT_BACKGROUND="red"
POWERLEVEL9K_CONTEXT_FOREGROUND="black"
POWERLEVEL9K_SHORTEN_DIR_LENGTH=1
ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets pattern cursor root line)
ZSH_HIGHLIGHT_PATTERNS=('rm -rf *' 'fg=white,bold,bg=red')
plugins=(colored-man-pages brew colorize pip python vi-mode)

# Source files
source "$HOME/.config/zsh/zprofile"
source "$ZSH/oh-my-zsh.sh"
source "$HOME/.config/zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.plugin.zsh"
source "$HOME/.config/zsh/zsh-autosuggestions/zsh-autosuggestions.plugin.zsh"
source "$HOME/.config/aliasrc"
source "$HOME/.config/shortcutrc"

# Alias overwrite
alias repr="source $HOME/.config/zsh/zshrc && cd -"

# PS1 management
# PS1="%B%{$fg[red]%}[%{$fg[yellow]%}%n%{$fg[green]%}@%{$fg[blue]%}%M:%{$fg[magenta]%}%~%{$fg[red]%}]%{$reset_color%}$%b "

# History file
HISTSIZE=
SAVEHIST=
HISTFILE=~/.config/zsh/history

# Less/Man colors
export LESS=-R

# Vim keys
bindkey -v
export KEYTIMEOUT=1

# Use vim keys in tab complete menu:
bindkey -M menuselect "h" vi-backward-char
bindkey -M menuselect "k" vi-up-line-or-history
bindkey -M menuselect "l" vi-forward-char
bindkey -M menuselect "j" vi-down-line-or-history
bindkey -v "^?" backward-delete-char

# Change cursor depending on vi mode
function zle-keymap-select {
  if [[ ${KEYMAP} == vicmd ]] ||
     [[ $1 = "block" ]]; then
    echo -ne "\e[1 q"
  elif [[ ${KEYMAP} == main ]] ||
       [[ ${KEYMAP} == viins ]] ||
       [[ ${KEYMAP} = "" ]] ||
       [[ $1 = "beam" ]]; then
    echo -ne "\e[5 q"
  fi
}
zle -N zle-keymap-select
zle-line-init() {
    zle -K viins
    echo -ne "\e[5 q"
}

# Bind lfcd to ctrl-o
lfcd () {
    tmp="$(mktemp)"
    lf -last-dir-path="$tmp" "$@"
    if [ -f "$tmp" ]; then
        dir="$(cat "$tmp")"
        rm -f "$tmp"
        [ -d "$dir" ] && [ "$dir" != "$(pwd)" ] && cd "$dir"
    fi
}
bindkey -s "^o" "lfcd\n"
