(setq user-init-file "/Users/frank/.config/emacs.d/init.el")
(setq user-emacs-directory "/Users/frank/.config/emacs.d")
(setq default-directory "/Users/frank/")
(setenv "HOME" "/Users/frank/")
(load user-init-file)
