#!/bin/bash

# Infinite history
HISTSIZE=
HISTFILESIZE=

# Formatting bash header
export PS1="\[$(tput setaf 1)\][\[$(tput setaf 3)\]\u\[$(tput setaf 2)\]@\[$(tput setaf 4)\]\h:\[$(tput setaf 5)\]\W\[$(tput setaf 1)\]]\[$(tput setaf 7)\]\\$ \[$(tput sgr0)\]"

# Load configs
[ -f "$HOME/.config/bash/bprofile" ] && source "$HOME/.config/bash/bprofile"
[ -f "$HOME/.config/shortcutrc" ] && source "$HOME/.config/shortcutrc"
[ -f "$HOME/.config/aliasrc" ] && source "$HOME/.config/aliasrc"
complete -C /usr/local/bin/vault vault

# Miniconda3
__conda_setup="$('/Users/frank/Miniconda3/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/Users/frank/Miniconda3/etc/profile.d/conda.sh" ]; then
        . "/Users/frank/Miniconda3/etc/profile.d/conda.sh"
    else
        export PATH="/Users/frank/Miniconda3/bin:$PATH"
    fi
fi
unset __conda_setup
