#!/bin/sh
alias h="cd ~/ && ls -l" \
    R="cd ~/repositories && ls -l" \
    sc="cd ~/.local/bin && ls -l" \
    ds="cd ~/.local/share && ls -l" \
    tb="cd ~/testbench && ls -l" \
    cfb="$EDITOR ~/.config/bash/bprofile" \
    cfbr="$EDITOR ~/.config/bash/bashrc" \
    cfz="$EDITOR ~/.config/zsh/.zprofile" \
    cfzr="$EDITOR ~/.config/zsh/.zshrc" \
    cfa="$EDITOR ~/.config/aliasrc" \
    cfs="$EDITOR ~/.config/shortcutrc" \
    cfv="$EDITOR ~/.config/nvim/init.vim" \
    cft="$EDITOR ~/.config/tmux/tmux.conf" \
